In [4]:
a, b = map(int, input().split())
c = a ** 2 + b ** 2
print(c)

25


In [7]:
s = input()
k = 0
for x in s:
    if (ord(x) >= 48) and (ord(x) <= 57):
        k = k + 1
print(k)


6


In [18]:
a = input().split()
k = 0
for s in a:
    s0 = []
    for i in s:
        s0.append(i)
    if (s0[0] == "A") and (s0[1] == "b") and (s0[2] == "o"):
        k = k + 1
print(k)

2


In [35]:
def task5(list_of_smth):
    list = []
    for i in range(1, len(list_of_smth), 2):
        list.append(list_of_smth[i])
    print(list[len(list)-2: 1: -1])

[11, 9, 7, 5]


In [ ]:
def task6(list1, list2, list3, list4):
    d1 = set(list1)
    d2 = set(list2)
    d3 = set(list3)
    d4 = set(list4)
    m1 = d1 | d4
    m2 = d2 | d3
    m = m1 & m2
    print(m)


In [55]:
def task7():
    import numpy as np
    np.random.seed(3)
    matrix = np.random.randint(36, size=36).reshape(6,6)
    matrix1 = np.delete(matrix, 5, 0)
    matrix2 = np.delete(matrix1, 0, 1)
    det = np.linalg.det(matrix2)
    return(matrix, det)

    

(array([[24,  3,  8,  0, 21, 19],
        [10, 10, 21, 32, 20, 29],
        [14, 26, 17, 26, 22,  2],
        [ 2,  1, 26,  5, 33, 29],
        [24,  7, 33, 15, 20, 30],
        [21, 14, 28,  0,  0, 18]]),
 -3219046.9999999986)

In [53]:
def task8(f, min_x, max_x, N, min_y, max_y):
    import numpy as np
    import matplotlib.pyplot as plt
    import matplotlib as mpl
    x = np.linspace(min_x, max_x, N)
    y = f(x)
    plt.xscale('log')
    plt.plot(x, y, "k.")
    plt.grid(True)
    plt.ylim((min_y, max_y))

    y1 = plt.derivative(f, x)
    plt.plot(x, y1)
    plt.show
    plt.savefig('function.jpg')



[[24  3  8  0 21 19]
 [10 10 21 32 20 29]
 [14 26 17 26 22  2]
 [ 2  1 26  5 33 29]
 [24  7 33 15 20 30]
 [21 14 28  0  0 18]]
[[ 3  8  0 21 19]
 [10 21 32 20 29]
 [26 17 26 22  2]
 [ 1 26  5 33 29]
 [ 7 33 15 20 30]]
